{% set name = "pynrrd" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mhe/pynrrd/archive/v{{ version }}.tar.gz
  sha256: 698fbf3384ce2f5637cb6c2991917f2208fccaeaebc0fdc20ab5fa0a8666c0c4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    # it looks like numpy is imported in the setup.py via
    # another import, but the package does not build against
    # the numpy C API - thus I am putting it in host here
    - numpy
  run:
    - python >=3.7
    - numpy
    - nptyping
    - typing_extensions

test:
  imports:
    - nrrd
    # the way pynrrd tests are organized in source tree (sub-pkg of nrrd pkg)
    # prevents us from running them. Import test must do.

about:
  home: https://github.com/mhe/pynrrd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple pure-python module for reading and writing nrrd files.

extra:
  recipe-maintainers:
    - beckermr
