{% set name = "pynrrd" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mhe/pynrrd/archive/v{{ version }}.tar.gz
  sha256: 0fba1c97ec2fc6a60ef1a56eec8f47d5f570168d22b4e8763565ff93f5366c27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    # it looks like numpy is imported in the setup.py via
    # another import, but the package does not build against
    # the numpy C API - thus I am putting it in host here
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - nrrd

about:
  home: https://github.com/mhe/pynrrd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple pure-python module for reading and writing nrrd files.

extra:
  recipe-maintainers:
    - beckermr
