{% set name = "pynrrd" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mhe/pynrrd/archive/v{{ version }}.tar.gz
  sha256: d0c98f607e6218768b1b8bd83edf7348a85f4f748d426857ae08264acbecfbca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    # it looks like numpy is imported in the setup.py via
    # another import, but the package does not build against
    # the numpy C API - thus I am putting it in host here
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - nrrd

about:
  home: https://github.com/mhe/pynrrd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple pure-python module for reading and writing nrrd files.

extra:
  recipe-maintainers:
    - beckermr
